# Generated by Django 2.1.2 on 2018-10-10 19:29

from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThreadMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(unique=True)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('password', encrypted_model_fields.fields.EncryptedCharField()),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='threadmessage',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='sluck_api.User'),
        ),
        migrations.AddField(
            model_name='threadmessage',
            name='dislikers',
            field=models.ManyToManyField(related_name='disliked_threads', to='sluck_api.User'),
        ),
        migrations.AddField(
            model_name='threadmessage',
            name='hashtags',
            field=models.ManyToManyField(related_name='thread_messages', to='sluck_api.Hashtag'),
        ),
        migrations.AddField(
            model_name='threadmessage',
            name='likers',
            field=models.ManyToManyField(related_name='liked_threads', to='sluck_api.User'),
        ),
        migrations.AddField(
            model_name='threadmessage',
            name='mentions',
            field=models.ManyToManyField(related_name='thread_mentions', to='sluck_api.User'),
        ),
        migrations.AddField(
            model_name='threadmessage',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='sluck_api.Message'),
        ),
        migrations.AddField(
            model_name='message',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='sluck_api.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='dislikers',
            field=models.ManyToManyField(related_name='disliked_messages', to='sluck_api.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='sluck_api.Group'),
        ),
        migrations.AddField(
            model_name='message',
            name='hashtags',
            field=models.ManyToManyField(related_name='messages', to='sluck_api.Hashtag'),
        ),
        migrations.AddField(
            model_name='message',
            name='likers',
            field=models.ManyToManyField(related_name='liked_messages', to='sluck_api.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='mentions',
            field=models.ManyToManyField(related_name='mentions', to='sluck_api.User'),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='groups', to='sluck_api.User'),
        ),
    ]
