# Generated by Django 2.1.2 on 2018-10-21 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sluck_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sluck_api.User')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sluck_api.Message')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='reactions',
            field=models.ManyToManyField(related_name='reactions', through='sluck_api.MessageReaction', to='sluck_api.User'),
        ),
    ]
