# Generated by Django 2.1.2 on 2018-10-21 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sluck_api', '0002_auto_20181021_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadMessageReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sluck_api.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='dislikers',
        ),
        migrations.RemoveField(
            model_name='message',
            name='likers',
        ),
        migrations.RemoveField(
            model_name='threadmessage',
            name='dislikers',
        ),
        migrations.RemoveField(
            model_name='threadmessage',
            name='likers',
        ),
        migrations.AddField(
            model_name='threadmessagereaction',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sluck_api.ThreadMessage'),
        ),
        migrations.AddField(
            model_name='threadmessage',
            name='reactions',
            field=models.ManyToManyField(related_name='thread_reactions', through='sluck_api.ThreadMessageReaction', to='sluck_api.User'),
        ),
    ]
