# Generated by Django 2.1.2 on 2018-10-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sluck_api', '0003_auto_20181021_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadmessage',
            name='reactions',
            field=models.ManyToManyField(related_name='thread_messages', through='sluck_api.ThreadMessageReaction', to='sluck_api.User'),
        ),
    ]
