# Generated by Django 2.1.2 on 2018-10-16 23:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sluck_api', '0003_user_token_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token_updated_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2018, 10, 16, 23, 43, 34, 393983, tzinfo=utc)),
        ),
    ]
