# Generated by Django 2.1.2 on 2018-10-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sluck_api', '0004_auto_20181005_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageDisLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('message_id', models.IntegerField()),
            ],
        ),
    ]
