# Generated by Django 2.1.2 on 2018-10-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sluck_api', '0006_group_usergroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageHashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField()),
                ('hashtag_id', models.IntegerField()),
            ],
        ),
    ]
