# Generated by Django 2.1.2 on 2018-10-22 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sluck_api', '0007_remove_user_token_updated_at'),
        ('sluck_api', '0004_auto_20181021_1920'),
    ]

    operations = [
    ]
