# Generated by Django 2.1.2 on 2018-10-09 16:13

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sluck_api', '0008_threaddislike_threadlike_threadmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
    ]
