# Generated by Django 2.1.2 on 2018-11-18 21:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sluck_api', '0009_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='notifactions',
            field=models.ManyToManyField(through='sluck_api.Notification', to=settings.AUTH_USER_MODEL),
        ),
    ]
