# Generated by Django 2.1.2 on 2018-11-18 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sluck_api', '0010_group_notifactions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='notifactions',
            new_name='notifications',
        ),
    ]
